export interface Message {
	side: 'left' | 'right';
	message: string;
}
export const messages: Message[] = [
	{ side: 'left', message: 'What is the square root of 9896?' },
	{ side: 'right', message: '99.4796' },
	{ side: 'left', message: 'Who was the second president of the United States?' },
	{ side: 'right', message: 'John Adams' },
	{ side: 'left', message: `What is the capital of Uzbekistan?` },
	{ side: 'right', message: `Tashkent.` },
	{ side: 'left', message: `Who discovered penicillin?` },
	{ side: 'right', message: `Alexander Fleming.` },
	{ side: 'left', message: `What is the formula for the area of a circle?` },
	{ side: 'right', message: `πr².` },
	{ side: 'left', message: `Who wrote the novel 'The Catcher in the Rye'?` },
	{ side: 'right', message: `J.D. Salinger.` },
	{ side: 'left', message: `What is the boiling point of water in Fahrenheit?` },
	{ side: 'right', message: `212°F.` },
	{ side: 'left', message: `Who is the current Prime Minister of Canada?` },
	{ side: 'right', message: `Justin Trudeau.` },
	{ side: 'left', message: `What is the largest planet in our solar system?` },
	{ side: 'right', message: `Jupiter.` },
	{ side: 'left', message: `Who composed the 'Moonlight Sonata'?` },
	{ side: 'right', message: `Ludwig van Beethoven.` },
	{ side: 'left', message: `What is the chemical symbol for gold?` },
	{ side: 'right', message: `Au.` },
	{ side: 'left', message: `Who is the author of 'The Great Gatsby'?` },
	{ side: 'right', message: `F. Scott Fitzgerald.` },
	{ side: 'left', message: `What is the tallest mountain in Africa?` },
	{ side: 'right', message: `Mount Kilimanjaro.` },
	{ side: 'left', message: `Who painted the 'Mona Lisa'?` },
	{ side: 'right', message: `Leonardo da Vinci.` },
	{ side: 'left', message: `What is the capital of Portugal?` },
	{ side: 'right', message: `Lisbon.` },
	{ side: 'left', message: `Who invented the telephone?` },
	{ side: 'right', message: `Alexander Graham Bell.` },
	{ side: 'left', message: `What is the largest desert in the world?` },
	{ side: 'right', message: `Sahara Desert.` },
	{ side: 'left', message: `Who wrote the play 'Hamlet'?` },
	{ side: 'right', message: `William Shakespeare.` },
	{ side: 'left', message: `What is the symbol for the element sodium?` },
	{ side: 'right', message: `Na.` },
	{ side: 'left', message: `Who was the first man to walk on the moon?` },
	{ side: 'right', message: `Neil Armstrong.` },
	{ side: 'left', message: `What is the currency of Japan?` },
	{ side: 'right', message: `Yen.` },
	{ side: 'left', message: `Who was the founder of Microsoft?` },
	{ side: 'right', message: `Bill Gates.` },
	{ side: 'left', message: `What is the smallest country in the world?` },
	{ side: 'right', message: `Vatican City.` },
	{ side: 'left', message: `Who painted 'Starry Night'?` },
	{ side: 'right', message: `Vincent van Gogh.` },
	{ side: 'left', message: `What is the formula for the Pythagorean theorem?` },
	{ side: 'right', message: `a² + b² = c².` },
	{ side: 'left', message: `Who wrote the novel '1984'?` },
	{ side: 'right', message: `George Orwell.` },
	{ side: 'left', message: `What is the longest river in the world?` },
	{ side: 'right', message: `Nile River.` },
	{ side: 'left', message: `Who is the current President of France?` },
	{ side: 'right', message: `Emmanuel Macron.` },
	{ side: 'left', message: `What is the largest ocean in the world?` },
	{ side: 'right', message: `Pacific Ocean.` },
	{ side: 'left', message: `Who painted the 'Sistine Chapel Ceiling'?` },
	{ side: 'right', message: `Michelangelo.` },
	{ side: 'left', message: `What is the capital of Australia?` },
	{ side: 'right', message: `Canberra.` },
	{ side: 'left', message: `Who wrote the poem 'The Waste Land'?` },
	{ side: 'right', message: `T.S. Eliot.` },
	{ side: 'left', message: `What is the chemical symbol for oxygen?` },
	{ side: 'right', message: `O.` },
	{ side: 'left', message: `Who is the author of 'To Kill a Mockingbird'?` },
	{ side: 'right', message: `Harper Lee.` },
	{ side: 'left', message: `What is the highest mountain in the world?` },
	{ side: 'right', message: `Mount Everest.` },
	{ side: 'left', message: `Who invented the lightbulb?` },
	{ side: 'right', message: `Thomas Edison.` },
	{ side: 'left', message: `What is the capital of Thailand?` },
	{ side: 'right', message: `Bangkok.` },
	{ side: 'left', message: `Who wrote the novel 'Pride and Prejudice'?` },
	{ side: 'right', message: `Jane Austen.` },
	{ side: 'left', message: `What is the chemical symbol for carbon?` },
	{ side: 'right', message: `C.` },
	{ side: 'left', message: `Who painted 'The Last Supper'?` },
	{ side: 'right', message: `Leonardo da Vinci.` },
	{ side: 'left', message: `What is the currency of China?` },
	{ side: 'right', message: `Yuan.` },
	{ side: 'left', message: `Who was the first female Prime Minister of the United Kingdom?` },
	{ side: 'right', message: `Margaret Thatcher.` },
	{ side: 'left', message: `What is the largest country in the world by land area?` },
	{ side: 'right', message: `Russia.` }
];
